name: Deploy To Dev S3
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: |
          npm install 
          npm run build

      - name: AWS 인증 절차
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: S3 기존 파일들 삭제 후 새로 업로드~
        run: |
          aws s3 rm --recursive s3://dev-fe-wep 
          aws s3 cp ./dist s3://dev-fe-wep --recursive

      - name: cloudfront 캐시 무효화~
        run: |
          aws cloudfront create-invalidation --distribution-id E3IO1CKGFY31GY --paths "/*"
